# This is a basic workflow to help you get started with Actions

name: Create Release

on:
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    
    - name: Setup node
      uses: actions/setup-node@v1
      with:
        node-version: '12.x'

    - name: Install Node Dependencies
      run: npm install

    - name: Build vsix
      run: npm run package

    - uses: actions/upload-artifact@v2
      with:
        name: release
        path: ./*.vsix
